name: Deploy to Amazon ECS

on:
  push:
   branches:
    - main

env:
  AWS_REGION: us-west-2                    # set this to your preferred AWS region, e.g. us-west-1
  ECS_SERVICE: stress-simulator-service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: web-simulator                 # set this to your Amazon ECS cluster name
  CONTAINER_NAME: web-stress-simulator              # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
   pipeline:
    name: "CI/CD"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
      
      #Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Setup Docker Env
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      #Docker Build and Push the image to hub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/petclinic:${{ github.sha }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/web-stress-simulator:latest
      
      #Docker image digest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} 
      
      #Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      #Download ECS task definition for updating the docker image 
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition stress-simulator-task \
          --query taskDefinition > task-definition.json
          cat task-definition.json

      #Update Docker image-id into local task definition
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/web-stress-simulator:latest

      #Deploy the updated task definition to ECS cluster
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true